# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.3
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
install:
- ./install_swiftlint.sh
script:
- set -o pipefail && xcodebuild test -workspace Example/Shift.xcworkspace -scheme Shift-Example -sdk iphonesimulator13.2 ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint
- swiftlint lint Shift/Classes/